openapi: 3.0.0
info:
  title: Hotel Search API
  description: An API for searching hotels.
  version: 1.0.0
  contact:
    email: support@yourdomain.com
servers:
  - url: https://us-central1-gke-elastic-394012.cloudfunctions.net
paths:
  /hoteldata:
    post:
      summary: Search for hotels
      description: This endpoint allows you to search for hotels based on the provided criteria.
      operationId: searchHotels
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                q:
                  type: string
                  description: The search query
                  example: hotel in chennai
                check_in_date:
                  type: string
                  format: date
                  description: The check-in date
                  example: 2024-07-22
                check_out_date:
                  type: string
                  format: date
                  description: The check-out date
                  example: 2024-07-22
      responses:
        '200':
          description: A list of hotels
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hotel_class:
                      type: string
                      nullable: true
                      description: The class of the hotel
                      example: 5-star hotel
                    name:
                      type: string
                      description: The name of the hotel
                      example: Sheraton Grande Hotel Chennai
                    rate_per_night:
                      type: object
                      properties:
                        lowest:
                          type: string
                          description : The rate per night
                          example: $33
                        extracted_lowest:
                          type: number
                          description : The rate per night extracted
                          example: 33
                        before_taxes_fees:
                          type: string
                          description : The rate per night before the tax
                          example: $33
                        extracted_before_taxes_fees:
                          type: number
                          description : The rate per night before the tax
                          example: 33
                    rating:
                      type: number
                      format: float
                      description: The rating of the hotel
                      example: 4.8
                    total_rate:
                      type: object
                      properties:
                        lowest:
                          type: string
                          description : The rate per nights
                          example: $33
                        extracted_lowest:
                          type: number
                          description : The rate per nights extracted
                          example: 33
                        before_taxes_fees:
                          type: string
                          description : The rate per night before the tax
                          example: $33
                        extracted_before_taxes_fees:
                          type: number
                          description : The rate per night before the tax
                          example: 33
        '400':
          description: Invalid request parameters
        '401':
          description: Unauthorized (invalid API key)
        '500':
          description: Internal server error
